import { Injectable } from '@angular/core';
import { BehaviorSubject } from 'rxjs';

@Injectable({
  providedIn: 'root'
})
export class LanguageService {
  private currentLanguage = new BehaviorSubject<'sw' | 'en'>('en');

  constructor() {
    // Load language from localStorage if available
    const savedLang = localStorage.getItem('language') as 'sw' | 'en';
    if (savedLang) {
      this.currentLanguage.next(savedLang);
    }
  }

  setLanguage(lang: 'sw' | 'en'): void {
    this.currentLanguage.next(lang);
    localStorage.setItem('language', lang);
  }

  getLanguage(): 'sw' | 'en' {
    return this.currentLanguage.value;
  }

  getLanguageObservable() {
    return this.currentLanguage.asObservable();
  }

  translate(key: string): string {
    const translations: Record<'en' | 'sw', Record<string, string>> = {
      // English translations
      en: {
        'home': 'HOME',
        'publicationResources': 'PUBLICATION & RESOURCES',
        'careers': 'CAREERS',
        'about': 'ABOUT',
        'contact': 'CONTACT',
        'dashboard': 'DASHBOARD',
        'reports': 'REPORTS',
        'signIn': 'Sign in',
        'submitReport': 'Submit Report',
        'myReports': 'My Reports',
        'resources': 'Resources',
        'newsUpdates': 'News & Updates',
        'welcome': 'Welcome',
        'logout': 'Logout',
        'backToForms': 'Back to Forms',
        'switchForm': 'Switch Form',
        'loading': 'Loading',
        'connectionError': 'Connection Error',
        'errorLoadingForm': 'Error Loading Form',
        'retryConnection': 'Retry Connection',
        'backToFormsBtn': 'Back to Forms',
        'formTypeName': 'Form Type Name',
        'sectionName': 'Section Name',
        'submit': 'Submit',
        'cancel': 'Cancel',
        'success': 'Success',
        'submissionSuccessful': 'Your application has been submitted successfully!',
        'submissionFailed': 'Submission Failed',
        'errorSubmitting': 'There was an error submitting your form. Please try again.',
        'validationError': 'Validation Error',
        'fillRequiredFields': 'Please fill in all required fields before submitting.',
        'selectOption': 'Select Option',
        'required': 'Required',
        'welcomeToTPHPA': 'Welcome to TPHPA Portal',
        'Plant Health Pesticides Portal': 'Plant Health Pesticides Portal',
        'advancedReportingPortal': 'Advanced Reporting & Agricultural Management Portal',
        'getStartedToday': 'Get Started Today',
        'learnMore': 'Learn More',
        'Plant Health Protection': 'Plant Health Protection',
        'Pest Disease Management': 'Pest Disease Management',
        'exploreSolutions': 'Explore Solutions',
        'ourServices': 'Our Services',
        'Pesticides Regulation': 'Pesticides Regulation',
        'Safe Effective Pesticides': 'Safe Effective Pesticides',
        'viewPrograms': 'View Programs',
        'RESOURCES': 'RESOURCES',
        'Agricultural Technology': 'Agricultural Technology',
        'Innovative Solutions for Farmers': 'Innovative Solutions for Farmers',
        'exploreTech': 'Explore Tech',
        'Pesticides Management': 'Pesticides Management',
        'Quality Control and Safety': 'Quality Control and Safety',
        'safetyGuidelines': 'Safety Guidelines',
        'Health & Safety': 'Health & Safety',
        'Protecting Farmers and Communities': 'Protecting Farmers and Communities',
        'healthPrograms': 'Health Programs',
        'agriculturalExcellence': 'Agricultural Excellence',
        'modernFarmingSolutions': 'Modern Farming Solutions for Sustainable Growth',
        'riceProduction': 'Rice Production',
        'qualitySustainability': 'Quality & Sustainability for Food Security',
        'activeFarmers': 'Active Farmers',
        'processedApplications': 'Processed Applications',
        'satisfactionRate': 'Satisfaction Rate',
        'applicationCenter': 'Application Center',
        'Submit Reports Launch Application': 'Submit Reports Launch Application',
        'quickAccessManage': 'Quickly access and manage your financial applications and accountability forms with our streamlined digital platform.',
        'imprestApplication': 'Imprest Application',
        'requestAdvanceFunds': 'Request advance funds for official duties',
        'quickApprovalProcess': 'Quick approval process',
        'realTimeStatusTracking': 'Real-time status tracking',
        'digitalSubmission': 'Digital submission',
        'applyNow': 'Apply Now',
        'trackApplications': 'Track Applications',
        'imprestRetirement': 'Imprest Retirement',
        'submitAccountability': 'Submit accountability for funds received',
        'easyExpenseReporting': 'Easy expense reporting',
        'receiptUploadFeature': 'Receipt upload feature',
        'automatedCalculations': 'Automated calculations',
        'retireNow': 'Retire Now',
        'claimForm': 'Claim Form',
        'submitExpenseClaims': 'Submit expense claims for approval',
        'multipleClaimCategories': 'Multiple claim categories',
        'fastProcessing': 'Fast processing',
        'directPaymentOption': 'Direct payment option',
        'newClaim': 'New Claim',
        'viewMyClaims': 'View My Claims',
        'whyChooseTphpaPortal': 'Why Choose TPHPA Portal',
        'plantHealthPesticideBenefits': 'Experience the benefits of our digital transformation for plant health and pesticide management.',
        'whyChooseTphpa': 'Why Choose Our Platform',
        'benefitsDigitalTransformation': 'Experience the benefits of our digital transformation for agricultural management and financial processes.',
        'fastProcessingDesc': 'Reduce waiting times with our streamlined digital approval workflows.',
        'secureReliableDesc': 'Your data is protected with enterprise-grade security measures.',
        'mobileFriendlyDesc': 'Access the platform from any device, anywhere with internet connection.',
        'supportDesc': 'Get help whenever you need it with our dedicated support team.',
        'LatestNewsUpdates': 'Latest News Updates',
        'latestNewsUpdateAdvertisement': 'Latest News Updates & Advertisement',
        'stayInformed': 'Stay informed with the latest announcements, events, and agricultural developments.',
        'failedLoadAdvertisements': 'Failed to Load Advertisements',
        'tryAgainLater': 'Please try again later or contact support if the problem persists.',
        'retry': 'Retry',
        'noCurrentAdvertisements': 'No Current Advertisements',
        'checkBackLater': 'Check back later for the latest news and updates.',
        'readyToGetStarted': 'Ready to Get Started?',
        'joinThousands': 'Join thousands of agricultural professionals who are already using our platform to streamline their operations.',
        'signInCta': 'Sign In',
        'contactUsCta': 'Contact Us',
        'welcomeBack': 'Welcome Back',
        'signInToTPHPA': 'Sign in to your TPHPA account',
        'emailAddress': 'Email Address',
        'enterEmail': 'Enter your email address',
        'validEmailError': 'Please enter a valid email address',
        'password': 'Password',
        'enterPassword': 'Enter your password',
        'passwordRequired': 'Password is required',
        'rememberMe': 'Remember me',
        'forgotPassword': 'Forgot password?',
        'signInAccount': 'Sign In to Your Account',
        'orContinueWith': 'Or continue with',
        'google': 'Google',
        'microsoft': 'Microsoft',
        'noAccount': 'Don\'t have an account?',
        'contactAdmin': 'Contact administrator',
        'english': 'English',
        'swahili': 'Swahili',
        'tphpaDescription': 'Tanzania Public Health Professionals Association dedicated to improving health services nationwide.',
        'quickLinks': 'Quick Links',
        'aboutTPHPA': 'About TPHPA',
        'membership': 'Membership',
        'training': 'Training',
        'publications': 'Publications',
        'news': 'News',
        'services': 'Services',
        'reportSubmission': 'Report Submission',
        'jobAdvertisements': 'Job Advertisements',
        'imprestApplications': 'Imprest Applications',
        'certification': 'Certification',
        'complaints': 'Complaints',
        'contactUs': 'Contact Us',
        'address': 'P.O. Box 1234, Dar es Salaam, Tanzania',
        'workingHours': 'Monday - Friday: 8AM - 5PM',
        'governmentPartners': 'Government Partners',
        'copyright': 'TPHPA Portal. All Rights Reserved.',
        'privacyPolicy': 'Privacy Policy',
        'termsOfService': 'Terms of Service',
        'sitemap': 'Sitemap'
      },
      // Swahili translations
      sw: {
        'home': 'NYUMBANI',
        'publicationResources': 'UCHAPISHWAJI NA RASILIMALI',
        'careers': 'KAZI',
        'about': 'KUHUSU',
        'contact': 'WASILIANA',
        'dashboard': 'UBAO',
        'reports': 'RIPOTI',
        'signIn': 'Ingia',
        'submitReport': 'Wasilisha Ripoti',
        'myReports': 'Ripoti Zangu',
        'resources': 'Rasilimali',
        'newsUpdates': 'Habari na Sasisho',
        'welcome': 'Karibu',
        'logout': 'Ondoka',
        'backToForms': 'Rudi kwenye Fomu',
        'switchForm': 'Badilisha Fomu',
        'loading': 'Inapakia',
        'connectionError': 'Kosa la Muunganisho',
        'errorLoadingForm': 'Kosa la Kupakia Fomu',
        'retryConnection': 'Jaribu Tena Muunganisho',
        'backToFormsBtn': 'Rudi kwenye Fomu',
        'formTypeName': 'Jina la Aina ya Fomu',
        'sectionName': 'Jina la Sehemu',
        'submit': 'Wasilisha',
        'cancel': 'Ghairi',
        'success': 'Mafanikio',
        'submissionSuccessful': 'Maombi yako yamewasilishwa kwa mafanikio!',
        'submissionFailed': 'Uwasilishaji Umeshindikana',
        'errorSubmitting': 'Kulikuwa na kosa katika kuwasilisha fomu yako. Tafadhali jaribu tena.',
        'validationError': 'Kosa la Uthibitishaji',
        'fillRequiredFields': 'Tafadhali jaza sehemu zote zinazohitajika kabla ya kuwasilisha.',
        'selectOption': 'Chagua Chaguo',
        'required': 'Inahitajika',
        'welcomeToTPHPA': 'Karibu TPHPA Tovuti',
        'Plant Health Pesticides Portal': 'Jukwaa la Afya ya Mimea na Dawa za Wadudu',
        'advancedReportingPortal': 'Jukwaa la Juu la Ripoti na Usimamizi wa Kilimo',
        'getStartedToday': 'Fanya Kuanza Leo',
        'learnMore': 'Jifunze Zaidi',
        'Plant Health Protection': 'Ulinzi wa Afya ya Mimea',
        'Pest Disease Management': 'Usimamizi wa Wadudu na Magonjwa',
        'exploreSolutions': 'Chunguza Suluhisho',
        'ourServices': 'Huduma Zetu',
        'Pesticides Regulation': 'Udhibiti wa Dawa za Wadudu',
        'Safe Effective Pesticides': 'Dawa za Wadudu Salama na Zenye Ufanisi',
        'viewPrograms': 'Tazama Programu',
        'RESOURCES': 'RASILIMALI',
        'Agricultural Technology': 'Teknolojia ya Kilimo',
        'Innovative Solutions for Farmers': 'Suluhisho za Ubunifu kwa Wakulima',
        'exploreTech': 'Chunguza Teknolojia',
        'Pesticides Management': 'Usimamizi wa Dawa za Wadudu',
        'Quality Control and Safety': 'Udhibiti wa Ubora na Usalama',
        'safetyGuidelines': 'Miongozo ya Usalama',
        'Health & Safety': 'Afya na Usalama',
        'Protecting Farmers and Communities': 'Kulinda Wakulima na Jamii',
        'healthPrograms': 'Programu za Afya',
        'agriculturalExcellence': 'Ubora wa Kilimo',
        'modernFarmingSolutions': 'Suluhisho za Kilimo cha Kisasa kwa Ukuaji Endelevu',
        'riceProduction': 'Uzalisaji wa Mchele',
        'qualitySustainability': 'Ubora na Uendelevu kwa Usalama wa Chakula',
        'activeFarmers': 'Wakulima Wenye Shughuli',
        'processedApplications': 'Maombi Yaliyosindikwa',
        'satisfactionRate': 'Kiwango cha Kuridhika',
        'applicationCenter': 'Kituo cha Maombi',
        'Submit Reports Launch Application': 'Tuma Ripoti Anzisha Maombi',
        'quickAccessManage': 'Fikia na simamia maombi yako ya kifedha na fomu za uwajibikaji kwa haraka kupitia jukwaa letu la kidijitali lililoboreshwa.',
        'imprestApplication': 'Maombi ya Imprest',
        'requestAdvanceFunds': 'Omba fedha za mapema kwa ajili ya majukumu rasmi',
        'quickApprovalProcess': 'Mchakato wa idhini ya haraka',
        'realTimeStatusTracking': 'Ufuatiliaji wa hali halisi',
        'digitalSubmission': 'Uwasilishaji wa kidijitali',
        'applyNow': 'Omba Sasa',
        'trackApplications': 'Fuatilia Maombi',
        'imprestRetirement': 'Kustaafu Imprest',
        'submitAccountability': 'Wasilisha uwajibikaji wa fedha zilizopokelewa',
        'easyExpenseReporting': 'Ripoti rahisi ya matumizi',
        'receiptUploadFeature': 'Kipengele cha kupakia risiti',
        'automatedCalculations': 'Hesabu otomatiki',
        'retireNow': 'Staafu Sasa',
        'claimForm': 'Fomu ya Madai',
        'submitExpenseClaims': 'Wasilisha madai ya matumizi kwa idhini',
        'multipleClaimCategories': 'Aina nyingi za madai',
        'fastProcessing': 'Usindikaji wa haraka',
        'directPaymentOption': 'Chaguo la malipo ya moja kwa moja',
        'newClaim': 'Dai Jipya',
        'viewMyClaims': 'Tazama Madai Yangu',
        'whyChooseTphpaPortal': 'Kwa nini Uchague Tphpa Tovuti',
        'whyChoosePlatform': 'Kwa Nini Uchague Jukwaa Letu',
        'benefitsDigitalTransformation': 'Pata manufaa ya mabadiliko yetu ya kidijitali kwa usimamizi wa kilimo na michakato ya kifedha.',
        'fastProcessingDesc': 'Punguza muda wa kusubiri kupitia mifumo yetu iliyoboreshwa ya idhini ya kidijitali.',
        'secureReliableDesc': 'Data yako inalindwa na hatua za usalama wa kiwango cha biashara.',
        'mobileFriendlyDesc': 'Fikia jukwaa kutoka kifaa chochote, popote ulipo na mtandao.',
        'supportDesc': 'Pata msaada wakati wowote unapohitaji kupitia timu yetu ya msaada.',
        'LatestNewsUpdates': 'Habari na Sasisho za Hivi Karibuni',
        'stayInformed': 'Kaa na habari za matangazo ya hivi karibuni, matukio, na maendeleo ya kilimo.',
        'failedLoadAdvertisements': 'Imeshindwa Kupakia Matangazo',
        'tryAgainLater': 'Tafadhali jaribu tena baadaye au wasiliana na msaada ikiwa tatizo linaendelea.',
        'retry': 'Jaribu Tena',
        'noCurrentAdvertisements': 'Hakuna Matangazo ya Sasa',
        'checkBackLater': 'Rudi baadaye kwa habari na sasisho za hivi karibuni.',
        'readyToGetStarted': 'Uko Tayari Kuanza?',
        'joinThousands': 'Jiunge na maelfu ya wataalamu wa kilimo ambao tayari wanatumia jukwaa letu kuboresha shughuli zao.',
        'signInCta': 'Ingia',
        'contactUsCta': 'Wasiliana Nasi',
        'welcomeBack': 'Karibu Tena',
        'signInToTPHPA': 'Ingia kwenye akaunti yako ya TPHPA',
        'emailAddress': 'Anwani ya Barua Pepe',
        'enterEmail': 'Ingiza anwani yako ya barua pepe',
        'validEmailError': 'Tafadhali ingiza anwani ya barua pepe sahihi',
        'password': 'Nenosiri',
        'enterPassword': 'Ingiza nenosiri lako',
        'passwordRequired': 'Nenosiri linahitajika',
        'rememberMe': 'Nikumbuke',
        'forgotPassword': 'Umesahau nenosiri?',
        'signInAccount': 'Ingia kwenye Akaunti Yako',
        'orContinueWith': 'Au endelea na',
        'google': 'Google',
        'microsoft': 'Microsoft',
        'noAccount': 'Huna akaunti?',
        'contactAdmin': 'Wasiliana na msimamizi',
        'english': 'Kiingereza',
        'swahili': 'Kiswahili',
        'tphpaDescription': 'Shirikisho la Wataalamu wa Afya ya Umma Tanzania linalojishughulisha na uboreshaji wa huduma za afya nchini.',
        'quickLinks': 'Viungo vya Haraka',
        'aboutTPHPA': 'Kuhusu TPHPA',
        'membership': 'Uanachama',
        'training': 'Mafunzo',
        'publications': 'Machapisho',
        'news': 'Habari',
        'services': 'Huduma',
        'reportSubmission': 'Uwasilishaji wa Ripoti',
        'jobAdvertisements': 'Matangazo ya Kazi',
        'imprestApplications': 'Maombi ya Kibarua',
        'certification': 'Udhibitisho',
        'complaints': 'Malalamiko',
        'contactUs': 'Wasiliana Nasi',
        'address': 'S.L.P 1234, Dar es Salaam, Tanzania',
        'workingHours': 'Jumatatu - Ijumaa: 08:00 - 17:00',
        'governmentPartners': 'Washirika wa Serikali',
        'copyright': 'Shirikisho la Wataalamu wa Afya ya Umma. Haki zote zimehifadhiwa.',
        'privacyPolicy': 'Sera ya Faragha',
        'termsOfService': 'Masharti ya Matumizi',
        'sitemap': 'Ramani ya Tovuti',
        // Publications page translations
        'publicationsResources': 'Machapisho na Rasilimali',
        'accessOfficialDocuments': 'Fikia hati rasmi za TPHPA, miongozo, ripoti, na nyenzo za utafiti',
        'searchPublications': 'Tafuta machapisho...',
        'allTypes': 'Aina Zote',
        'annualReports': 'Ripoti za Mwaka',
        'guidelines': 'Miongozo',
        'manuals': 'Mikono',
        'regulations': 'Kanuni',
        'research': 'Utafiti',
        'download': 'Pakua',
        'loadMorePublications': 'Pakia Machapisho Zaidi',
        'moreInfoPublications': 'Kwa maelezo zaidi kuhusu machapisho ya TPHPA, wasiliana na kituo chetu cha maelezo.',
        // Resources page translations
        'tphpaResourcesCenter': 'Kituo cha Rasilimali cha TPHPA',
        'trainingMaterials': 'Gundua nyenzo za mafunzo kamili, miongozo ya wataalamu, na zana za kisasa zilizoundwa kwa wataalamu wa afya ya mimea kote Tanzania',
        'searchResources': 'Tafuta rasilimali, miongozo, mikono...',
        'allCategories': 'Zote',
        'trainingMaterial': 'Nyenzo ya Mafunzo',
        'guide': 'Mwongozo',
        'handbook': 'Kitabu cha Mikono',
        'protocol': 'Itifaki',
        'template': 'Kiolezo',
        'toolkit': 'Seti ya Zana',
        'loadMoreResources': 'Pakia Rasilimali Zaidi',
        'noResourcesFound': 'Hakuna rasilimali zilizopatikana',
        'adjustSearchFilters': 'Jaribu kurekebisha maneno yako ya utafutaji au vichujio vya kategoria',
        'clearFilters': 'Futa Vichujio',
        'loadingMoreResources': 'Inapakia rasilimali zaidi...',
        'qualityResources': 'Rasilimali za Ubora',
        'expertCuratedMaterials': 'Nyenzo zilizochaguliwa na wataalamu kwa ubora wa afya ya mimea',
        'communitySupport': 'Msaada wa Jamii',
        'connectProfessionals': 'Unganisha na wataalamu kote Tanzania',
        'certifiedContent': 'Maudhui Yaliyothibitishwa',
        'officialApprovedMaterials': 'Nyenzo rasmi za mafunzo zilizoidhinishwa na TPHPA',
        // About page translations
        'protectingHeritage': 'Kulinda Urithi wa Afya ya Mimea wa Tanzania',
        'trustedPartner': 'Mamlaka ya Afya ya Mimea na Dawa za Wadudu ya Tanzania - Mshirika wako wa kuaminika katika kulinda ubora wa kilimo, kuhakikisha usalama wa chakula, na kukuza mazoea endelevu ya ukulima katika taifa letu',
        'purposeDirection': 'Madhumuni na Mwelekeo Wetu',
        'mission': 'Dhamira Yetu',
        'missionDesc': 'Kulinda na kuimarisha afya ya mimea kote Tanzania, kuhakikisha matumizi ya dawa za wadudu kwa uwajibikaji, na kukuza usalama wa chakula kupitia mazoea endelevu ya kilimo ambayo yanafaidi taifa letu na jamii.',
        'vision': 'Maono Yetu',
        'visionDesc': 'Tanzania ambapo afya ya mimea inalindwa kwa kiwango cha juu, dawa za wadudu zinatumika kwa usalama, na kilimo kinachangia kwa kiasi kikubwa katika maendeleo ya kitaifa na ustawi.',
        'coreValues': 'Maadili Yetu Msingi',
        'integrity': 'Uadilifu',
        'integrityDesc': 'Tunashikilia viwango vya juu zaidi vya uaminifu, uwazi, na mwenendo wa kimaadili katika shughuli zetu zote na mwingiliano.',
        'collaboration': 'Ushirikiano',
        'collaborationDesc': 'Tunashirikiana kikamilifu na washiriki, wakulima, na jamii ili kufikia malengo ya pamoja ya ubora wa kilimo.',
        'innovation': 'Ubunifu',
        'innovationDesc': 'Tunakumbatia teknolojia za kisasa na mbinu za ubunifu ili kuendelea kuboresha ulinzi wa afya ya mimea.',
        'sustainability': 'Uendelevu',
        'sustainabilityDesc': 'Tunapigania mazoea ya uwajibikaji wa mazingira ambayo huhakikisha uendelevu wa muda mrefu wa kilimo kwa vizazi vijavyo.',
        'whatWeDo': 'Tunachofanya',
        'plantQuarantine': 'Kuarizi Mimea',
        'plantQuarantineDesc': 'Kuzuia kuanzishwa na kuenea kwa wadudu na magonjwa ya mimea yanayohatarisha sekta yetu ya kilimo.',
        'pesticideRegulation': 'Udhibiti wa Dawa za Wadudu',
        'pesticideRegulationDesc': 'Kuhakikisha matumizi salama, yenye ufanisi, na ya uwajibikaji ya dawa za wadudu ili kulinda mazao na mazingira.',
        'qualityAssurance': 'Uhakikisho wa Ubora',
        'qualityAssuranceDesc': 'Kudumisha viwango vikali vya afya ya mimea na bidhaa za kilimo ili kuhakikisha ubora na usalama.',
        // Careers page translations
        'careerOpportunities': 'Fursa za Kazi',
        'shapeFutureTPHPA': 'Umbie Mustakabali Wako katika TPHPA',
        'joinTPHPA': 'Jiunge na mamlaka kuu ya afya ya mimea ya Tanzania na uwe sehemu ya kubadilisha kilimo kupitia ubunifu, utaalamu, na kujitolea.',
        'viewOpenPositions': 'Tazama Nafasi Zilizofunguliwa',
        'exploreTraining': 'Chunguza Mafunzo',
        'careerDevelopmentPathways': 'Njia za Maendeleo ya Kazi',
        'technicalTrack': 'Njia ya Kiufundi',
        'technicalTrackDesc': 'Bobea katika ukaguzi wa afya ya mimea, uchambuzi wa dawa za wadudu, na mbinu za maabara. Endelea kutoka kwa Mkaguzi Mdogo hadi Mtaalamu Mkuu wa Kiufundi.',
        'plantHealthInspector': 'Mkaguzi wa Afya ya Mimea',
        'pesticideAnalyst': 'Mchambuzi wa Dawa za Wadudu',
        'laboratorySpecialist': 'Mtaalamu wa Maabara',
        'seniorTechnicalOfficer': 'Afisa Mkuu wa Kiufundi',
        'managementTrack': 'Njia ya Usimamizi',
        'managementTrackDesc': 'Kuza ujuzi wa uongozi na usimamizi katika udhibiti wa kilimo na sera. Endelea kutoka kwa Afisa hadi nafasi za kiwango cha Mkurugenzi.',
        'regulatoryOfficer': 'Afisa wa Udhibiti',
        'unitManager': 'Meneja wa Kitengo',
        'departmentDirector': 'Mkurugenzi wa Idara',
        'seniorManagement': 'Usimamizi wa Juu',
        'researchTrack': 'Njia ya Utafiti',
        'researchTrackDesc': 'Zingatia utafiti, ukuzaji wa sera, na ushirikiano wa kimataifa. Jenga utaalamu katika sayansi ya kilimo na mifumo ya udhibiti.',
        'researchAssistant': 'Msaidizi wa Utafiti',
        'policyAnalyst': 'Mchambuzi wa Sera',
        'researchScientist': 'Mwanasayansi wa Utafiti',
        'principalResearcher': 'Mtafiti Mkuu',
        'trainingDevelopmentPrograms': 'Programu za Mafunzo na Maendeleo',
        'leadershipTraining': 'Mafunzo ya Uongozi',
        'leadershipTrainingDesc': 'Ukuzaji wa ujuzi wa usimamizi na uongozi kwa majukumu ya usimamizi na menejimenti.',
        'technicalSkills': 'Ujuzi wa Kiufundi',
        'technicalSkillsDesc': 'Mafunzo ya hali ya juu katika utambuzi wa afya ya mimea, uchambuzi wa dawa za wadudu, na uzingatiaji wa kanuni.',
        'internationalPrograms': 'Programu za Kimataifa',
        'internationalProgramsDesc': 'Programu za kubadilishana na vyeti vya kimataifa katika afya na usalama wa kilimo.',
        'professionalDevelopment': 'Maendeleo ya Kitaalamu',
        'professionalDevelopmentDesc': 'Fursa za kujifunza zinazoendelea ikiwa ni pamoja na warsha, seminari, na kozi za mtandaoni.',
        'careerProgressionFramework': 'Mfumo wa Maendeleo ya Kazi',
        'entryLevel': 'Kiwango cha Kuingia',
        'entryLevelDesc': 'Jenga maarifa na ujuzi wa msingi katika uwanja uliochagua.',
        'midLevel': 'Kiwango cha Kati',
        'midLevelDesc': 'Chukua majukumu magumu zaidi na majukumu ya uongozi.',
        'seniorLevel': 'Kiwango cha Juu',
        'seniorLevelDesc': 'Ongeza mipango ya kimkakati na uwaongoze wafanyakazi wadogo.',
        'professionalDevelopmentResources': 'Rasilimali za Maendeleo ya Kitaalamu',
        'learningResources': 'Rasilimali za Kujifunza',
        'learningResourcesDesc': 'Fikia nyenzo kamili za kujifunza, kozi za mtandaoni, na vyeti vya kitaalamu katika usimamizi wa afya ya mimea na dawa za wadudu.',
        'onlineLearningPlatform': 'Jukwaa la Kujifunza Mtandaoni',
        'technicalManuals': 'Mikono ya Kiufundi na Miongozo',
        'professionalCertifications': 'Veti vya Kitaalamu',
        'researchPublications': 'Machapisho ya Utafiti',
        'mentorshipProgram': 'Programu ya Umentori',
        'mentorshipProgramDesc': 'Unganisha na wataalamu wenye uzoefu kwa mwongozo wa kazi, ukuzaji wa ujuzi, na uhamishaji wa maarifa ndani ya TPHPA.',
        'oneOnOneMentoring': 'Umentori wa Mtu kwa Mtu',
        'careerGuidanceSessions': 'Vikao vya Mwongozo wa Kazi',
        'skillDevelopmentPlans': 'Mipango ya Ukuzaji wa Ujuzi',
        'leadershipCoaching': 'Ukozi wa Uongozi',
        'advanceCareerToday': 'Endeleza Kazi Yako Leo',
        'contactHRTeam': 'Chukua hatua inayofuata katika safari yako ya kitaalamu katika TPHPA. Unganisha na timu yetu ya Rasilimali Watu ili kuchunguza fursa za maendeleo na njia za maendeleo ya kazi.',
        'contactHRDepartment': 'Wasiliana na Idara ya HR',
        'callHROffice': 'Piga Simu Ofisi ya HR'
      }
    };

    const currentLang = this.getLanguage();
    return translations[currentLang][key] || key;
  }
}
