services:
  - type: web
    name: portal-frontend
    env: node
    buildCommand: cd tphpa && npm install && ng build --configuration=production && cd ../backend && npm install
    startCommand: cd tphpa && node dist/portal/server/server.mjs
    envVars:
      - key: NODE_ENV
        value: production
